#基本はgithub.comのリポジトリを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'
# neocompleteはluaが入っていないと使えません。有効化をするために、
# sudo apt-get install vim-gnome
# などでluaを入れましょう

[[plugins]]
repo = 'Shougo/neomru.vim'
[[plugins]]
repo = 'kana/vim-smartchr'
